### ISSUE TITLE
Swift 2.3 / iOS 10 SDK Support

### ISSUE THREAD

**Issue by renssies** [Adyen/adyen-checkout-ios#18] opened 2016-09-12 14:39 UTC
Currently the checkout seems to break (at least in the example) when the migrator is used to migrate to Swift 2.3. I keep getting "Encryption error".

**Comment by xslim** [comment] 2016-09-13 12:32
Would you mind giving us more information? "Encryption error" can be caused by different issues.

**Comment by renssies** [comment] 2016-09-13 12:41
If you use the migration tool for Swift 2.3 there is a change in `ADYRSACRyptor.swift`, It's just the new swift for loop:
![screen shot 2016-09-13 at 14 35 22](https://cloud.githubusercontent.com/assets/830094/18473854/677a0f98-79bf-11e6-8368-ed943e68cf5c.png)

However, once this has been changed and you build the project against the iOS 10 SDK. You will get "Encryption error" in the sample project. 

Looking at the logs, the problem is caused by a RSA key that is a "Duplicate" the when adding to keychain, but is "Not found" when retrieving from Keychain. This can be easily solved in `TKRSACryptor.h` by adding `kSecAttrAccessible` to the query when updating or adding the key to keychain. 

However once this change has been made, the same project will report it is unable to decrypt the payment data. So the encryption of the payment data is still going wrong. 

I tried to fix it it myself, but was only able to fix the keychain issues: https://github.com/renssies/adyen-checkout-ios

**Comment by olutsenko** [comment] 2016-09-14 09:13
Hi Rens,

Thanks a lot for detailed description of the issue.

We see that Keychain Access issue is related to already known issue being reported in iOS long time ago (https://forums.developer.apple.com/thread/4743). Apple said the issue was fixed in iOS 9.3 but we see more and more people report it is back on Xcode 8. It might be related to the developer tools as some people report it's being happening having debugger attached to the app.

From what we see, there is no issue if you run example code directly on a device. You will start experience problems if you run app in Simulator. 

There is a workaround for Simulator suggested by other developers — turn on 'Keychain Sharing' in the app target 'Capabilities' tab. After this, the app should work fine in the Simulator.

We continue looking into the issue and update you if we figure out a better solution.

Please let us know if it helps.

Regards,
Oleg

**Comment by olutsenko** [comment] 2016-09-14 09:22
One more link — https://forums.developer.apple.com/message/178596#178596

**Comment by renssies** [comment] 2016-09-14 09:29
I know of the keychain issue, I've had it before. But in my last case I fixed the keychain issue, ran the example app on the device but got the decrypt error from the server in the example project. Non of the keychain results were an error in that case

**Comment by olutsenko** [comment] 2016-09-14 10:38
How did you fix it? Because we didn't change any code apart from the Swift loop change. Application works fine on a device.

Can you try to discard your changes for the Keychain logic and try to run on a device?

**Comment by renssies** [comment] 2016-09-14 10:55
Hmm, now it does seem to work. Not sure what I did wrong the last few days. Thanks. 

Want me to make a pull request for the Swift 2.3 changes? The changes were actually introduced in swift 2.2

**Comment by xslim** [comment] 2016-09-14 11:21
Sure, make a PR and we will review it.

**Closed by xslim** 2016-09-14 11:21 UTC
